import {
  Company,
  CompanyContactPerson,
  CompanyAddress,
  Department,
  CostCenter,
  EmployeeOrgAssignment,
} from '@/types/company';

export const mockCompanies: Company[] = [
  {
    id: 'comp-1',
    companyCode: 'ABC-TRD',
    legalName: 'ABC Trading SARL',
    displayName: 'ABC Trading',
    countryCode: 'LB',
    defaultCurrencyId: 'cur-1', // USD
    taxRegistrationNumber: 'LB123456789',
    nssfRegistrationNumber: 'NSSF-LB-001',
    commercialRegisterNumber: 'CR-2024-001',
    commercialRegisterPlace: 'Beirut',
    responsiblePersonName: 'Hassan Khalil',
    responsiblePersonTitle: 'General Manager',
    responsiblePersonPhone: '+961-1-123456',
    responsiblePersonEmail: 'hassan@abctrading.com',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'comp-2',
    companyCode: 'CEDARS-PAY',
    legalName: 'Cedars Payroll Demo SAL',
    displayName: 'Cedars Payroll',
    countryCode: 'LB',
    defaultCurrencyId: 'cur-2', // LBP
    taxRegistrationNumber: 'LB987654321',
    nssfRegistrationNumber: 'NSSF-LB-002',
    commercialRegisterNumber: 'CR-2024-002',
    commercialRegisterPlace: 'Beirut',
    responsiblePersonName: 'Mona Nassar',
    responsiblePersonTitle: 'Finance Director',
    responsiblePersonPhone: '+961-1-654321',
    responsiblePersonEmail: 'mona@cedars.com',
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockCompanyContacts: CompanyContactPerson[] = [
  // ABC Trading SARL contacts
  {
    id: 'contact-1',
    companyId: 'comp-1',
    fullName: 'Hassan Khalil',
    title: 'General Manager',
    email: 'hassan@abctrading.com',
    phone: '+961-1-123456',
    mobile: '+961-71-111111',
    contactType: 'legal_representative',
    nationalIdNumber: 'LB-123456',
    isPrimary: true,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'contact-2',
    companyId: 'comp-1',
    fullName: 'Rania Khoury',
    title: 'Finance Manager',
    email: 'rania@abctrading.com',
    phone: '+961-1-123457',
    mobile: '+961-71-222222',
    contactType: 'payroll_contact',
    nationalIdNumber: 'LB-123457',
    isPrimary: false,
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'contact-3',
    companyId: 'comp-1',
    fullName: 'Ahmad Farraj',
    title: 'Tax Consultant',
    email: 'ahmad@abctrading.com',
    phone: '+961-1-123458',
    mobile: '+961-71-333333',
    contactType: 'tax_contact',
    nationalIdNumber: 'LB-123458',
    isPrimary: false,
    isActive: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
  // Cedars Payroll contacts
  {
    id: 'contact-4',
    companyId: 'comp-2',
    fullName: 'Mona Nassar',
    title: 'Finance Director',
    email: 'mona@cedars.com',
    phone: '+961-1-654321',
    mobile: '+961-71-444444',
    contactType: 'legal_representative',
    nationalIdNumber: 'LB-654321',
    isPrimary: true,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'contact-5',
    companyId: 'comp-2',
    fullName: 'Pierre Antoun',
    title: 'HR Manager',
    email: 'pierre@cedars.com',
    phone: '+961-1-654322',
    mobile: '+961-71-555555',
    contactType: 'payroll_contact',
    nationalIdNumber: 'LB-654322',
    isPrimary: false,
    isActive: true,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
];

export const mockCompanyAddresses: CompanyAddress[] = [
  // ABC Trading SARL addresses
  {
    id: 'addr-1',
    companyId: 'comp-1',
    addressType: 'registered',
    countryCode: 'LB',
    governorate: 'Mount Lebanon',
    district: 'Aley',
    town: 'Aley',
    neighborhood: 'Downtown',
    street: 'Main Street',
    building: 'ABC Building',
    propertyNumber: '123',
    floor: '5',
    postalCode: '2020',
    fullAddress: 'ABC Building, Main Street, Aley, Mount Lebanon, Lebanon',
    isPrimary: true,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'addr-2',
    companyId: 'comp-1',
    addressType: 'notification',
    countryCode: 'LB',
    governorate: 'Beirut',
    district: 'Ashrafieh',
    town: 'Beirut',
    neighborhood: 'Business District',
    street: 'Rue Verdun',
    building: 'Trade Center',
    propertyNumber: '456',
    floor: '10',
    postalCode: '1100',
    fullAddress: 'Trade Center, Rue Verdun, Ashrafieh, Beirut, Lebanon',
    isPrimary: false,
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  // Cedars Payroll addresses
  {
    id: 'addr-3',
    companyId: 'comp-2',
    addressType: 'registered',
    countryCode: 'LB',
    governorate: 'Beirut',
    district: 'Hamra',
    town: 'Beirut',
    neighborhood: 'West Beirut',
    street: 'Hamra Street',
    building: 'Cedars Tower',
    propertyNumber: '789',
    floor: '12',
    postalCode: '1105',
    fullAddress: 'Cedars Tower, Hamra Street, Beirut, Lebanon',
    isPrimary: true,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockDepartments: Department[] = [
  // ABC Trading departments
  {
    id: 'dept-1',
    companyId: 'comp-1',
    parentDepartmentId: null,
    departmentCode: 'SALES',
    name: 'Sales',
    description: 'Sales and business development',
    managerEmployeeId: 'emp-1',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dept-2',
    companyId: 'comp-1',
    parentDepartmentId: 'dept-1',
    departmentCode: 'SALES-DOMESTIC',
    name: 'Domestic Sales',
    description: 'Local market sales team',
    managerEmployeeId: null,
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'dept-3',
    companyId: 'comp-1',
    parentDepartmentId: 'dept-1',
    departmentCode: 'SALES-EXPORT',
    name: 'Export Sales',
    description: 'International sales team',
    managerEmployeeId: null,
    isActive: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
  {
    id: 'dept-4',
    companyId: 'comp-1',
    parentDepartmentId: null,
    departmentCode: 'FINANCE',
    name: 'Finance',
    description: 'Finance and accounting',
    managerEmployeeId: 'emp-2',
    isActive: true,
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-04T00:00:00Z',
  },
  // Cedars Payroll departments
  {
    id: 'dept-5',
    companyId: 'comp-2',
    parentDepartmentId: null,
    departmentCode: 'HR',
    name: 'Human Resources',
    description: 'HR and recruitment',
    managerEmployeeId: null,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'dept-6',
    companyId: 'comp-2',
    parentDepartmentId: null,
    departmentCode: 'PAYROLL',
    name: 'Payroll',
    description: 'Payroll processing',
    managerEmployeeId: null,
    isActive: true,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
];

export const mockCostCenters: CostCenter[] = [
  // ABC Trading cost centers
  {
    id: 'cc-1',
    companyId: 'comp-1',
    parentCostCenterId: null,
    costCenterCode: 'SALES',
    name: 'Sales Operations',
    description: 'Sales department costs',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cc-2',
    companyId: 'comp-1',
    parentCostCenterId: null,
    costCenterCode: 'ADMIN',
    name: 'Administration',
    description: 'General administrative costs',
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'cc-3',
    companyId: 'comp-1',
    parentCostCenterId: null,
    costCenterCode: 'MARKETING',
    name: 'Marketing',
    description: 'Marketing and promotion costs',
    isActive: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
  // Cedars Payroll cost centers
  {
    id: 'cc-4',
    companyId: 'comp-2',
    parentCostCenterId: null,
    costCenterCode: 'OPERATIONS',
    name: 'Operations',
    description: 'Operational costs',
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockEmployeeOrgAssignments: EmployeeOrgAssignment[] = [
  {
    id: 'assign-1',
    companyId: 'comp-1',
    employeeId: 'emp-1',
    departmentId: 'dept-1',
    costCenterId: 'cc-1',
    positionTitle: 'Sales Manager',
    effectiveFrom: '2024-01-01',
    effectiveTo: null,
    isPrimary: true,
    assignmentReason: 'Initial assignment',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'assign-2',
    companyId: 'comp-1',
    employeeId: 'emp-2',
    departmentId: 'dept-4',
    costCenterId: 'cc-2',
    positionTitle: 'Finance Manager',
    effectiveFrom: '2024-01-01',
    effectiveTo: null,
    isPrimary: true,
    assignmentReason: 'Initial assignment',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'assign-3',
    companyId: 'comp-2',
    employeeId: 'emp-3',
    departmentId: 'dept-5',
    costCenterId: 'cc-4',
    positionTitle: 'HR Executive',
    effectiveFrom: '2024-01-05',
    effectiveTo: null,
    isPrimary: true,
    assignmentReason: 'Initial assignment',
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];
