import { Currency, Bank, ThirdPartyPaymentProvider, TreatyCountry } from '@/types/foundation';

export const mockCurrencies: Currency[] = [
  // ABC Trading currencies
  {
    id: 'cur-1',
    companyId: 'comp-1',
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    decimalPrecision: 2,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cur-2',
    companyId: 'comp-1',
    code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'L.L.',
    decimalPrecision: 0,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cur-3',
    companyId: 'comp-1',
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    decimalPrecision: 2,
    isActive: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  // Cedars Payroll currencies
  {
    id: 'cur-4',
    companyId: 'comp-2',
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    decimalPrecision: 2,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'cur-5',
    companyId: 'comp-2',
    code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'L.L.',
    decimalPrecision: 0,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockBanks: Bank[] = [
  // ABC Trading banks
  {
    id: 'bank-1',
    companyId: 'comp-1',
    name: 'Bank Audi',
    code: 'AUDI',
    swiftCode: 'AUDBLBBX',
    countryCode: 'LB',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'bank-2',
    companyId: 'comp-1',
    name: 'BLOM Bank',
    code: 'BLOM',
    swiftCode: 'BLOMLBBX',
    countryCode: 'LB',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'bank-3',
    companyId: 'comp-1',
    name: 'Byblos Bank',
    code: 'BYBLOS',
    swiftCode: 'BYBALBBX',
    countryCode: 'LB',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  // Cedars Payroll banks
  {
    id: 'bank-4',
    companyId: 'comp-2',
    name: 'Bank Audi',
    code: 'AUDI',
    swiftCode: 'AUDBLBBX',
    countryCode: 'LB',
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'bank-5',
    companyId: 'comp-2',
    name: 'Credit Suisse',
    code: 'CS',
    swiftCode: 'CREDIT',
    countryCode: 'CH',
    isActive: true,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-06T00:00:00Z',
  },
];

export const mockPaymentProviders: ThirdPartyPaymentProvider[] = [
  // ABC Trading providers
  {
    id: 'prov-1',
    companyId: 'comp-1',
    name: 'OMT',
    code: 'OMT',
    providerType: 'money_transfer',
    supportsBulkPayment: false,
    requiresPhoneNumber: true,
    requiresNationalId: true,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-2',
    companyId: 'comp-1',
    name: 'Whish',
    code: 'WHISH',
    providerType: 'wallet',
    supportsBulkPayment: true,
    requiresPhoneNumber: true,
    requiresNationalId: false,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-3',
    companyId: 'comp-1',
    name: 'Cash Payment',
    code: 'CASH',
    providerType: 'cash',
    supportsBulkPayment: false,
    requiresPhoneNumber: false,
    requiresNationalId: false,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  // Cedars Payroll providers
  {
    id: 'prov-4',
    companyId: 'comp-2',
    name: 'Whish',
    code: 'WHISH',
    providerType: 'wallet',
    supportsBulkPayment: true,
    requiresPhoneNumber: true,
    requiresNationalId: false,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'prov-5',
    companyId: 'comp-2',
    name: 'Cash Payment',
    code: 'CASH',
    providerType: 'cash',
    supportsBulkPayment: false,
    requiresPhoneNumber: false,
    requiresNationalId: false,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];

export const mockTreatyCountries: TreatyCountry[] = [
  // ABC Trading treaty countries
  {
    id: 'country-1',
    companyId: 'comp-1',
    countryName: 'Lebanon',
    isoCode: 'LB',
    hasTaxTreaty: false,
    hasNssfReciprocity: false,
    specialTreatmentType: undefined,
    effectiveFrom: undefined,
    effectiveTo: null,
    notes: undefined,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'country-2',
    companyId: 'comp-1',
    countryName: 'France',
    isoCode: 'FR',
    hasTaxTreaty: true,
    hasNssfReciprocity: true,
    specialTreatmentType: undefined,
    effectiveFrom: '2024-01-01',
    effectiveTo: null,
    notes: 'EU member state',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'country-3',
    companyId: 'comp-1',
    countryName: 'Syria',
    isoCode: 'SY',
    hasTaxTreaty: false,
    hasNssfReciprocity: false,
    specialTreatmentType: undefined,
    effectiveFrom: undefined,
    effectiveTo: null,
    notes: undefined,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  // Cedars Payroll treaty countries
  {
    id: 'country-4',
    companyId: 'comp-2',
    countryName: 'Lebanon',
    isoCode: 'LB',
    hasTaxTreaty: false,
    hasNssfReciprocity: false,
    specialTreatmentType: undefined,
    effectiveFrom: undefined,
    effectiveTo: null,
    notes: undefined,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'country-5',
    companyId: 'comp-2',
    countryName: 'Germany',
    isoCode: 'DE',
    hasTaxTreaty: true,
    hasNssfReciprocity: true,
    specialTreatmentType: undefined,
    effectiveFrom: '2024-01-01',
    effectiveTo: null,
    notes: 'EU member state',
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-05T00:00:00Z',
  },
];
